### ISSUE TITLE
computeAccessValues taking over 2 minutes and 75% of the total compute time

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/browsochrones#1]
Two notes (and why this is a Github issue).
1. What changed recently in `get-surface` that would cause it to take an order of magnitude longer to compute than it did before? Most of it seems to be coming from `computeAccessValues`. Or is it the data?
2. Should we be computing access values while generating the surface? What are the benefits vs computing it afterwards?

**Comment by trevorgerhardt** [comment]
Also, meant to mention that I temporarily disabled it in `get-surface` for now.

**Comment by mattwigway** [comment]
Are you still using the data out of S3? I added path information to the format but didn't update the files in S3 - if you use the static server in r5 it works. Otherwise there's a data format mismatch and all bets are off. Generating isohrones and accessibility is taking about 2-3 seconds for me.

**Comment by mattwigway** [comment]
computeAccessValues is taking 50 seconds and >90% of compute time in Chrome
