### ISSUE TITLE
Pseudo-colorize Isochrone

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/browsochrones#10]
We need to be able to see the differences in travel times and one band up to 60 minutes.

**Comment by mattwigway** [comment]
![image](https://cloud.githubusercontent.com/assets/566958/11640561/2b141cc4-9d01-11e5-898c-f38dc26acfe5.png)

**Comment by mattwigway** [comment]
so pretty. Breaks in hue occur every 15 minutes.

**Comment by mattwigway** [comment]
Although it does kind of look like what happens when you spill water on something printed by an inkjet printer.
